lang:
  scoreboard:
    title: "&6&lHub"
    normal:
      - "&7&o&m----------------------------"
      - "&eCurrent Players"
      - "&f%online%"
      - ""
      - "&eRank"
      - "&f%rankcolor%%rank%"
      - ""
      - "&cwww.%website%"
      - "&7&m----------------------------"
    queue:
      - "&7&o&m----------------------------"
      - "&eCurrent Players"
      - "&f%online%"
      - ""
      - "&eRank"
      - "&f%rankcolor%%rank%"
      - ""
      - "&6Queue &c(%queuename%)"
      - "&e#%queueposition% / %queuesize%"
      - "&f(%queueest%)"
      - ""
      - "&cwww.%website%"
      - "&7&m----------------------------"
  joinmessage:
    - "%line%"
    - "&eWelcome to the &6&lCombo Network&e, %rankcolor%%username%&e!"
    - ""
    - "&7 * &e&lWebsite: &fwww.%website%"
    - "&7 * &e&lStore: &f%store%"
    - "&7 * &e&lTwitter: &ftwitter.com/%twitter%"
    - "&7 * &e&lTeamSpeak: &f%teamspeak%"
    - "%line%"
  commands:
    setspawn:
      callback: "&aUpdated the spawn location."
  toggledplayersoff: "&dYou toggled player visibility off!"
  toggledplayerson: "&dYou toggled player visibility on!"
  queue:
    nolives: "&cYou cannot join the queue as you are currently deathbanned and have no soulbound lives, purchase lives at protocol.rip/store"
    revived: "&aYou have used one of your lives to revive yourself, you now have %lives%, rejoin the queue to play."

config:
  website: "combo.rip"
  twitter: "ComboRIP"
  discord: "discord.gg/ComboRIP"
  store: "combo.rip/store"
  teamspeak: "ts.combo.rip"

settings:
  spawnlocation: "world|0|100|0"
  yaw: 0
  pitch: 0
  doublejump:
    multiply: 1.9
    y: 1.2
  voidtp:
    enabled: true
    position: -15

items:
  selector:
    material: clock
    amount: 1
    slot: 0
    data: 0
    name: "&6Server Selector"
    lore:
      - "%line%"
      - "&6&lRIGHT CLICK &eto open the &fserver selector&e."
      - "%line%"
    action: "openmenu/serverselector"
  test:
    material: dhelm
    amount: 1
    slot: 8
    data: 0
    name: "&cTest Item &7(Click)"
    lore:
      - "%line%"
      - "&6&lRIGHT CLICK &eto open the &fserver selector&e."
      - "%line%"
    action: "sendmessage/&cHello there &a%player% &estore: %store%"
  toggleplayersoffitem:
    material: lever
    amount: 1
    slot: 4
    data: 0
    name: "&cTurn Off Players &7(Click)"
    lore:
      - "%line%"
      - "&6&lRIGHT CLICK &eto turn off players"
      - "%line%"
    action: "toggleplayers/false/toggleplayersonitem"
  toggleplayersonitem:
    material: lever
    amount: 1
    slot: 69420 #Blank slot
    data: 0
    name: "&cTurn On Players &7(Click)"
    lore:
      - "%line%"
      - "&6&lRIGHT CLICK &eto turn on players"
      - "%line%"
    action: "toggleplayers/true/toggleplayersoffitem"

inventories:
  serverselector:
    title: "&CTest %player%"
    items:
      kitmap:
        material: ghelm
        amount: 1
        slot: 0
        data: 0
        name: "&e&lKITS"
        lore:
          - "%line%"
          - "&6&lRIGHT CLICK &eto join the &fKits Queue."
          - "%line%"
        action: "queue/kit"
      hcf:
        material: dhelm
        amount: 1
        slot: 8
        data: 0
        name: "&e&lHCF"
        lore:
          - "%line%"
          - "&6&lRIGHT CLICK &eto join the &fHCF Queue."
          - "%line%"
        action: "queue/hcf  "

tab:
  mode: REGULAR
  startposition: 4
  0:
    0: "&cHello"
  1:
    0: "&aWorld!"
  2:
    0: "&d:D"
